// Code generated by go-bindata.
// sources:
// store/schema/1_init.sql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _storeSchema1_initSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xd0\xb1\x6e\xc2\x30\x14\x85\xe1\xfd\x3e\xc5\x19\x13\xb5\x2c\x95\x98\x98\x4c\xe2\xb6\x56\x83\x83\x1c\xbb\x82\xa9\x0a\xd8\x02\xab\x01\x47\x8e\x51\xd5\xb7\xaf\x60\xa0\x0c\x9e\xbf\xff\x4a\x57\x67\x36\xc3\xd3\xc9\x1f\x62\x9f\x1c\xcc\x48\x54\x29\xce\x34\x87\x66\xcb\x86\x43\xbc\x42\xb6\x1a\x7c\x23\x3a\xdd\x61\x17\xc2\xf7\x84\x82\x00\x6f\x21\xa4\x86\x91\x9d\x78\x93\xbc\xbe\x45\xd2\x34\x0d\x98\xd1\xed\x97\x90\x95\xe2\x2b\x2e\xf5\x33\x01\xc9\xa7\xc1\xe1\x93\xa9\xea\x9d\xa9\xe2\x65\x3e\x2f\x6f\xe5\x95\xfa\x4b\x3a\x86\x98\xb7\xf1\xb2\x1b\xfc\x74\x74\xb6\xbe\x3e\x96\x4d\xfc\xa9\x3f\x38\x13\x87\xbc\x5a\x37\xed\xa3\x1f\x93\x0f\x67\x68\xbe\xd1\x77\xd8\x47\xd7\x27\x67\x97\xbf\xf9\xbb\x3b\x0b\x9b\x0f\xd6\x4a\xac\x98\xda\xe2\x83\x6f\x51\x78\x5b\x52\xb9\x20\x7a\x5c\xb1\x0e\x3f\x67\xa2\x5a\xb5\xeb\xff\x15\x1f\x17\x5c\xd0\x5f\x00\x00\x00\xff\xff\x7c\xc9\x6b\xa4\x74\x01\x00\x00")

func storeSchema1_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_storeSchema1_initSql,
		"store/schema/1_init.sql",
	)
}

func storeSchema1_initSql() (*asset, error) {
	bytes, err := storeSchema1_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "store/schema/1_init.sql", size: 372, mode: os.FileMode(420), modTime: time.Unix(1489644255, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"store/schema/1_init.sql": storeSchema1_initSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"store": &bintree{nil, map[string]*bintree{
		"schema": &bintree{nil, map[string]*bintree{
			"1_init.sql": &bintree{storeSchema1_initSql, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
